Repository thoth-station/kebechet, pull requests merged in 2018-11, with the labels that each got.

#185 Monitor AICoE/prometheus-flatliner repository
  config/thoth.yaml
Labels: approved, size/XS

#179 added metrics-exports
  .zuul.yaml
  config/thoth.yaml
Labels: approved, size/M, size/S

#187 Set env variables to suppress pipenv emojis
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#190 Remove markers from requirements file
  kebechet/managers/update/update.py
Labels: approved, size/XS

#183 Monitor Thoth's management API
  config/thoth.yaml
Labels: approved, size/S

#192 Add thoth-python to monitored repos
  config/thoth.yaml
Labels: size/S

#191 Add long description for PyPI
  setup.py
Labels: approved, size/XS
