Repository thoth-station/kebechet, pull requests merged in 2018-06, with the labels that each got.

#8 Add missing gitpython dependency
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/M

#10 Explicitly name env variables to configure options
  kebechet/cli.py
Labels: approved, size/XS

#17 updated username to reviewer in OWNERS
  OWNERS
Labels: approved, size/XS

#11 Deployment of kebechet
  Dockerfile
  README.rst
  docker-entrypoint.sh
  openshift/buildConfig-template.yaml
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/secret-template.yaml
  playbooks/deprovision.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-kebechet-bot/tasks/main.yaml
  playbooks/roles/thoth-kebechet-imagestreams/tasks/main.yaml
  playbooks/roles/thoth-ssh-key-check/tasks/main.yaml
Labels: approved, size/L

#13 Add support for requirements.txt
  kebechet/cli.py
  kebechet/exception.py
  kebechet/update.py
Labels: approved, lgtm, size/L

#21 Fix syntax error in Ansible scripts
  playbooks/roles/thoth-kebechet-bot/tasks/main.yaml
Labels: approved, lgtm, size/XS

#22 Update old PRs on top of the current master
  README.rst
  kebechet/update.py
Labels: approved, do-not-merge/work-in-progress, size/M

#23 added initial zuul config
  .zuul.yaml
Labels: approved, size/S

#25 added upload to pypi
  .coafile
  .zuul.yaml
  Pipfile
  Pipfile.lock
  kebechet/cli.py
  kebechet/config.py
  kebechet/exception.py
  kebechet/github.py
  kebechet/update.py
  kebechet/utils.py
Labels: approved, size/XL

#26 reparing 1.0.0-rc.4
  CHANGELOG.md
  kebechet/__init__.py
Labels: size/S

#28 Explicitly update dependencies to their latest version
  kebechet/update.py
Labels: size/S

#30 Install gcc-c++ for native builds
  Dockerfile
Labels: approved, size/XS

#29 using only zuul for releaseing to pypi
  .travis.yml
Labels: approved, size/S

#27 Add a generic webhook for triggering builds
  openshift/buildConfig-template.yaml
Labels: approved, size/XS
