Repository thoth-station/kebechet, pull requests merged in 2018-07, with the labels that each got.

#35 Fix local setup
  Dockerfile
Labels: approved

#34 some minor tweaks
  README.rst
  kebechet/cli.py
  openshift/buildConfig-template.yaml
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  openshift/secret-template.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-kebechet-bot/tasks/main.yaml
  playbooks/roles/thoth-ssh-key-check/tasks/main.yaml
Labels: approved

#40 just minor wording tweaks
  kebechet/cli.py
  kebechet/config.py
Labels: approved, enhancement

#42 Remove pydocstyle from direct dependencies
  Pipfile
Labels: approved

#45 Automatic update of dependency pipenv from 2018.5.18 to 2018.7.1
  Pipfile.lock
Labels: bot

#47 Automatic update of dependency pytest from 3.6.2 to 3.6.3
  Pipfile.lock
Labels: approved, bot

#53 Fix hash computation
  kebechet/managers/update.py
Labels: approved

#55 Initial dependency lock
  Pipfile.lock
Labels: approved, bot

#75 Adjust template labels
  openshift/buildConfig-template.yaml
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  openshift/secret-template.yaml
Labels: approved

#76 Add Sesheta to monitored repos
  config/thoth.yaml
Labels: approved

#85 Initial dependency lock
  Pipfile.lock
Labels: bot

#90 Fix missing packages
  setup.py
Labels: approved

#89 Introduce version manager for automatic version releases
  config/thoth.yaml
  kebechet/config.py
  kebechet/managers/__init__.py
  kebechet/managers/version/__init__.py
  kebechet/managers/version/version.py
  kebechet/source_management.py
Labels: approved

#91 Let only maintainers release new packages
  config/thoth.yaml
  kebechet/managers/version/version.py
Labels: approved

#99 Remove unused import
  kebechet/cli.py
Labels: approved

#105 Implement semver and calver for automated releases
  Pipfile
  Pipfile.lock
  kebechet/managers/version/README.rst
  kebechet/managers/version/version.py
Labels: approved, size/XL

#108 Initial dependency lock
  Pipfile.lock
Labels: bot

#110 Fix version handling issues
  kebechet/config.py
  kebechet/managers/version/version.py
Labels: size/S

#104 Inspect also version.py for version information
  kebechet/managers/version/version.py
Labels: size/XS

#113 Fix tagging of commit
  kebechet/managers/version/version.py
Labels: approved, size/XS

#119 Introduce Pipfile requirements.txt manager
  kebechet/managers/__init__.py
  kebechet/managers/pipfile_requirements/README.rst
  kebechet/managers/pipfile_requirements/__init__.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/utils.py
Labels: approved, size/L

#116 Do not tag commits
  kebechet/managers/version/version.py
Labels: approved, size/XS

#117 Use related instead of fixes
  kebechet/managers/version/version.py
Labels: approved, size/XS

#125 Print Kebechet version on startup
  kebechet/cli.py
Labels: approved, size/XS

#124 Fix user assignment to issue
  kebechet/source_management.py
Labels: approved, size/XS

#127 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#129 Do calendar release with full year
  kebechet/managers/version/version.py
Labels: approved, size/XS

#131 Version can be stated in version.py
  kebechet/managers/version/README.rst
Labels: approved, size/XS

#133 [WIP] now with a build trigger
  .zuul.yaml
Labels: size/S, size/XS

#136 Expand configuration to start using pipfile-requirements
  config/thoth.yaml
Labels: approved, size/L

#134 Fix f-string
  kebechet/utils.py
Labels: approved, size/XS

#132 Do not cache images in build config
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#128 Compute changelog on releases
  kebechet/managers/version/version.py
Labels: approved, size/M
