Repository thoth-station/kebechet, pull requests merged in 2018-09, with the labels that each got.

#144 Enable change log files on Thoth repos
  config/thoth.yaml
Labels: approved, size/S

#145 Log activities done during changelog computation
  kebechet/managers/version/version.py
Labels: approved, size/XS

#149 Fix computing of changelog
  kebechet/managers/info/info.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/update/update.py
  kebechet/utils.py
Labels: approved, size/S

#151 added thamos project
  config/thoth.yaml
Labels: size/M

#153 Monitor AICoE/log-anomaly-detector for updates
  config/thoth.yaml
Labels: size/XS

#154 Fix repo name
  config/thoth.yaml
Labels: size/XS

#159 Be case insensitive with issue titles triggering new versions
  kebechet/managers/version/version.py
Labels: approved, size/S
