Repository thoth-station/kebechet, pull requests merged in 2019-09, with the labels that each got.

#238 Add build-analyzers to monitored repos
  config/thoth.yaml
Labels: approved, size/S

#240 Propagate deployment name for sentry environment
  openshift/cronJob-template.yaml
  openshift/job-kebechet-template.yaml
Labels: approved, size/S, size/XS

#241 Update templates and cli options
  openshift/secret-template.yaml
Labels: approved, size/M, size/S

#242 Add package-analyzer to monitored repos
  config/thoth.yaml
Labels: approved, size/S

#244 Fix wrong slug for the sesheta repo
  config/thoth.yaml
Labels: size/XS
