Repository thoth-station/kebechet, pull requests merged in 2019-06, with the labels that each got.

#213 relocked to fix CVE-2019-11324
  Pipfile.lock
Labels: approved, size/L

#217 Add CermakM to list of thoth-lab maintainers
  config/thoth.yaml
Labels: approved, size/XS

#218 using the new trigger-build zuul job
  .zuul.yaml
Labels: approved, size/M, size/S, size/XS

#219 Add invectio for management
  config/thoth.yaml
Labels: size/S

#221 Configure starting deadline seconds to large number
  openshift/cronJob-template.yaml
Labels: approved, size/XS
