Repository thoth-station/kebechet, pull requests merged in 2019-08, with the labels that each got.

#225 CronJobs are now in apiVersion v1beta1
  openshift/cronJob-template.yaml
Labels: size/XS

#222 Nowait
  Dockerfile
  Pipfile
  Pipfile.lock
  app.sh
  kebechet/cli.py
  kebechet/config.py
  kebechet/managers/__init__.py
  kebechet/managers/manager.py
  kebechet/managers/thoth_advise/README.rst
  kebechet/managers/thoth_advise/__init__.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/thoth_provenance/README.rst
  kebechet/managers/thoth_provenance/__init__.py
  kebechet/managers/thoth_provenance/thoth_provenance.py
  kebechet/services.py
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/job-kebechet-template.yaml
Labels: approved, size/XXL

#233 Fix list in YAML
  kebechet/managers/thoth_provenance/README.rst
Labels: approved, size/XS

#235 Remove osiris and osiris observer
  config/thoth.yaml
Labels: size/M

#236 Small changes to env names
  kebechet/cli.py
  openshift/job-kebechet-template.yaml
Labels: approved, size/S

#237 Use UBI8 as base image
  Dockerfile
Labels: approved, size/XS
