Repository thoth-station/kebechet, pull requests merged in 2019-02, with the labels that each got.

#194 Add osiris and osiris build-observer
  config/thoth.yaml
Labels: size/M

#196 Add build-watcher to monitored repos
  config/thoth.yaml
Labels: size/XS

#197 Update year in sources
  kebechet/cli.py
  kebechet/config.py
  kebechet/enums.py
  kebechet/exception.py
  kebechet/managers/info/info.py
  kebechet/managers/info/messages.py
  kebechet/managers/manager.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
  kebechet/source_management.py
  kebechet/utils.py
Labels: size/S

#198 Add init-job to monitored repos
  config/thoth.yaml
Labels: size/XS

#199 added graph-sync-scheduler to configuration file
  config/thoth.yaml
Labels: size/S

#201 Do not use update manager in graph-sync-scheduler
  config/thoth.yaml
Labels: approved, size/XS

#202 Use Thoth's init_logging routine
  Pipfile
  Pipfile.lock
  kebechet/cli.py
  kebechet/managers/info/messages.py
Labels: approved, size/L
