Repository thoth-station/kebechet, pull requests merged in 2019-03, with the labels that each got.

#203 Kill Kebechet after 2 hours if it was not able compute results
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#204 that part of the webhook url is not required
  .zuul.yaml
Labels: approved, size/XS

#205 Do not forget to install thoth-common
  requirements.txt
Labels: size/XS

#208 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S
