Repository thoth-station/kebechet, pull requests merged in 2019-10, with the labels that each got.

#246 Update README.rst
  kebechet/managers/version/README.rst
Labels: approved, size/XS

#243 Do not monitor conu repo
  config/thoth.yaml
Labels: approved, size/S

#247 relocked to fix CVE-2018-18074
  Pipfile.lock
Labels: approved, size/XL

#252 Add thoth-station/messaging to monitored repos
  config/thoth.yaml
Labels: approved, size/S

#255 added the AICoE repos
  config/thoth.yaml
Labels: approved, size/L

#257 Development packages are not mandatory in Pipfile
  kebechet/managers/update/update.py
Labels: approved, size/XS

#259 Support for AICoE ludus
  config/thoth.yaml
Labels: approved, size/XS

#261 Enable version manager for AICoE/prometheus-api-client-python
  config/thoth.yaml
Labels: approved, size/S

#262 added an annotation to each object created
  openshift/buildConfig-template.yaml
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-kebechet-template.yaml
  openshift/secret-template.yaml
Labels: approved, enhancement, size/L

#264 Adjust cache location when run in the cluster due to perms
  app.sh
Labels: approved, size/XS

#268 Adjust Pipenv cache in the correct place
  Dockerfile
  app.sh
Labels: approved, size/XS

#269 use /tmp for a .cache directory
  Dockerfile
Labels: approved, do-not-merge/needs-rebase, size/XS

#265 added Thoth's Stub-API Repository
  config/thoth.yaml
Labels: approved, do-not-merge/needs-rebase, size/S

#270 Fix permission issues
  Dockerfile
Labels: approved, do-not-merge/needs-rebase, size/XS

#271 github ref point to master
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#273 Use the generic webhook for build trigger
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#274 updated templates with annotations
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  openshift/job-kebechet-template.yaml
  openshift/secret-template.yaml
Labels: approved, size/XS

#276 Sort repositories based upon their dependencies
  config/thoth.yaml
Labels: approved, size/L
