Repository thoth-station/kebechet, pull requests merged in 2020-07, with the labels that each got.

#464 keep the application up-to-date with pre-commit
  .github/workflows/codeql.yml
  .thoth.yaml
  Dockerfile
  app.sh
  config/thoth.yaml
  kebechet/__init__.py
  kebechet/cli.py
  kebechet/config.py
  kebechet/managers/README.rst
  kebechet/managers/__init__.py
  kebechet/managers/info/README.rst
  kebechet/managers/info/__init__.py
  kebechet/managers/info/info.py
  kebechet/managers/info/messages.py
  kebechet/managers/manager.py
  kebechet/managers/pipfile_requirements/__init__.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/thoth_advise/README.rst
  kebechet/managers/thoth_advise/__init__.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/thoth_provenance/README.rst
  kebechet/managers/thoth_provenance/__init__.py
  kebechet/managers/thoth_provenance/thoth_provenance.py
  kebechet/managers/update/README.rst
  kebechet/managers/update/__init__.py
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
  kebechet/managers/version/__init__.py
  kebechet/managers/version/version.py
  kebechet/managers/version/version_test.py
  kebechet/payload_parser.py
  kebechet/services.py
  kebechet/utils.py
  openshift/configMap-template.yaml
  openshift/cronJob-template.yaml
  openshift/kebechet-template.yaml
  playbooks/deprovision.yaml
  playbooks/provision.yaml
  playbooks/roles/thoth-kebechet-bot/tasks/main.yaml
  playbooks/roles/thoth-kebechet-imagestreams/tasks/main.yaml
  requirements.txt
  setup.py
  workflows/templates/kebechet-job.yaml
Labels: approved, size/XXL

#467 Automatic update of dependency thoth-common from 0.13.13 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#470 Precommit fixes
  .coafile
  MANIFEST.in
  kebechet/config.py
  kebechet/exception.py
  kebechet/managers/info/info.py
  kebechet/managers/manager.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
  kebechet/managers/version/version_test.py
  kebechet/payload_parser.py
  kebechet/services.py
Labels: approved, size/L

#469 Cronjob cleanup-job can be archived
  config/thoth.yaml
Labels: approved, size/S

#472 Automatic update of dependency thamos from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: approved, bot, size/M

#471 Automatic update of dependency gitpython from 3.1.3 to 3.1.7
  Pipfile.lock
Labels: approved, bot, size/M

#468 Relock fix
  kebechet/managers/update/update.py
Labels: approved, size/M

#474 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/S

#475 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/S

#476 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/M

#477 Formatted commit messages with backticks.
  kebechet/managers/version/version.py
Labels: approved, size/XS

#465 Remove thoth-station/package-analyzer
  config/thoth.yaml
Labels: approved, size/S

#480 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/L

#481 Automatic update of dependency pytest from 5.4.3 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/L
