Repository thoth-station/kebechet, pull requests merged in 2020-02, with the labels that each got.

#298 Support for thoth package-update-job
  config/thoth.yaml
Labels: approved, size/XS

#299 Add thoth-station/s2i repository
  config/thoth.yaml
Labels: approved, size/S

#301 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#302 Update thoth.yaml - removed non existing repo.
  config/thoth.yaml
Labels: approved, size/XS

#297 Webhook payload as argument
  app.sh
  kebechet/cli.py
  kebechet/config.py
  kebechet/exception.py
  kebechet/payload_parser.py
  kebechet/services.py
Labels: approved, size/L

#305 Ogr migration
  Pipfile
  Pipfile.lock
  kebechet/exception.py
  kebechet/managers/manager.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/thoth_provenance/thoth_provenance.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
  kebechet/payload_parser.py
  kebechet/source_management.py
  requirements.txt
Labels: approved, size/XXL

#309 Automatic update of dependency requests from 2.22.0 to 2.23.0
  Pipfile.lock
Labels: bot, size/S

#312 Fixed ogr migration errors
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
  kebechet/source_management.py
Labels: approved, size/M

#304 Manager events
  kebechet/config.py
  kebechet/managers/info/info.py
  kebechet/managers/manager.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/thoth_provenance/thoth_provenance.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
  kebechet/payload_parser.py
Labels: approved, size/M

#314 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/M

#316 Fixed lambda x
  kebechet/managers/version/version.py
Labels: approved, size/XS

#315 A big step towards general AI
  kebechet/managers/version/version.py
Labels: size/S

#317 Adjust .thoth.yaml configuration file
  .thoth.yaml
Labels: size/XS

#318 Closes release request if no change
  kebechet/managers/version/version.py
Labels: approved, size/XS

#320 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/M
