Repository thoth-station/kebechet, pull requests merged in 2020-03, with the labels that each got.

#324 Fix latest
  Pipfile
  Pipfile.lock
  kebechet/config.py
  kebechet/managers/manager.py
  requirements.txt
Labels: approved, size/M

#325 Thoth sourcemanagement
  Pipfile
  Pipfile.lock
  kebechet/__init__.py
  kebechet/config.py
  kebechet/enums.py
  kebechet/managers/manager.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/thoth_provenance/thoth_provenance.py
  kebechet/managers/update/update.py
  kebechet/payload_parser.py
  kebechet/services.py
  kebechet/source_management.py
  kebechet/utils.py
  requirements.txt
Labels: approved, size/L

#327 Fixed messages and create initial lock commits
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
Labels: approved, size/M

#329 Automatic update of dependency click from 7.0 to 7.1.1
  Pipfile.lock
Labels: bot, size/M

#330 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/XS

#332 Automatic update of dependency pytest from 5.3.5 to 5.4.0
  Pipfile.lock
Labels: bot

#333 Automatic update of dependency pytest from 5.4.0 to 5.4.1
  Pipfile.lock
Labels: bot, size/XS

#334 Automatic update of dependency pyyaml from 5.3 to 3.13
  Pipfile.lock
Labels: bot, size/M

#328 Check standard package in pipfile.lock
  kebechet/managers/update/update.py
Labels: approved, size/XS

#337 add maintainer for thoth-station/messaging
  config/thoth.yaml
Labels: approved
