Repository thoth-station/kebechet, pull requests merged in 2020-08, with the labels that each got.

#486 Automatic update of dependency thamos from 0.10.6 to 0.11.0
  Pipfile.lock
Labels: approved, bot, size/M

#487 Document CHANGELOG.md file generation and assignees
  kebechet/managers/version/README.rst
Labels: approved, size/XS

#488 Automatic update of dependency thoth-common from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#489 Automatic update of dependency thamos from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: approved, bot, size/M

#490 Automatic update of dependency pytest-cov from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: approved, bot, size/M

#484 Optionally generate intelligent release logs using Glyph
  Pipfile
  Pipfile.lock
  kebechet/managers/version/README.rst
  kebechet/managers/version/version.py
  requirements.txt
Labels: approved, size/L

#495 Fixed added context to multiple version string error.
  Pipfile.lock
  kebechet/managers/version/version.py
Labels: approved, size/L

#499 Fix formatting when smart changelogs are created
  kebechet/managers/version/version.py
Labels: approved, size/XS

#498 Enable smart logs by default
  kebechet/managers/version/version.py
Labels: approved, size/XS

#496 Add release templates to let Kebechet release itself
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M

#505 Release of version 1.0.2
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/L

#510 Updated to pipenv 2020.8.13 and locked
  Dockerfile
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/L

#512 Release of version 1.0.3
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/XL

#515 Revert "Updated to pipenv 2020.8.13 and locked"
  Dockerfile
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/L

#518 Skip empty new lines in update manager
  kebechet/managers/update/update.py
Labels: approved, size/XS

#519 Add GitHub's PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#521 Release of version 1.0.4
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/S
