Repository thoth-station/kebechet, pull requests merged in 2020-06, with the labels that each got.

#414 Add version release for advise-reporter
  config/thoth.yaml
Labels: approved, size/S

#415 Add thoth-station/datasets
  config/thoth.yaml
Labels: approved, size/S

#416 add pre-commit config
  .pre-commit-config.yaml
Labels: approved, size/M

#417 Correct template
  openshift/secret-template.yaml
Labels: approved, size/XS

#418 Add repo for solver error classifier
  config/thoth.yaml
Labels: approved, size/S

#420 Release of version 1.0.1
  CHANGELOG.md
  kebechet/__init__.py
Labels: bot, size/L

#422 Perform manual update of dependencies
  Pipfile.lock
Labels: size/M

#428 Fix semver to use non-deprecated methods.
  kebechet/managers/version/version.py
Labels: approved, size/S

#429 Fresh piplock
  Pipfile.lock
Labels: approved, size/M

#431 Remove old member
  config/thoth.yaml
Labels: approved, size/XS

#432 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.0
  Pipfile.lock
Labels: bot, size/S

#433 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: bot, size/XS

#435 Automatic update of dependency semver from 2.10.1 to 2.10.2
  Pipfile.lock
Labels: bot, size/XS

#436 Automatic update of dependency pytest-timeout from 1.4.0 to 1.4.1
  Pipfile.lock
Labels: bot, size/XS

#438 Change logger to info to monitor on cluster
  kebechet/managers/version/version.py
Labels: approved, size/XS

#441 Fix yaml error
  kebechet/managers/version/version.py
Labels: approved, size/XS

#442 Automatic update of dependency thoth-common from 0.13.11 to 0.13.12
  Pipfile.lock
Labels: bot, size/XS

#443 New piplock
  Dockerfile
  Pipfile.lock
Labels: approved, size/M

#445 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: bot, size/S

#448 Pin older version of Pipenv during the build
  Dockerfile
Labels: approved, size/XS

#447 Make config parsing more safe
  kebechet/config.py
Labels: approved, size/S

#449 Piplock using 2018
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#450 keep wf for SLI
  openshift/kebechet-template.yaml
Labels: approved, size/XS

#452 Limit version release log to 300
  kebechet/managers/version/version.py
Labels: approved

#454 Automatic update of dependency thoth-sourcemanagement from 0.2.9 to 0.3.0
  Pipfile.lock
Labels: approved, bot

#456 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: approved, bot

#457 Remove result-api and workload-operator
  config/thoth.yaml
Labels: approved

#458 Remove graph-sync-scheduler
  config/thoth.yaml
Labels: approved

#460 Remove build-analyzers
  config/thoth.yaml
Labels: approved

#425 Add CodeQL security scanning
  .github/workflows/codeql.yml
Labels: approved, size/M
