Repository thoth-station/kebechet, pull requests merged in 2020-11, with the labels that each got.

#587 Enabled github app authentication
  README.rst
  kebechet/managers/manager.py
Labels: approved, size/S

#589 Remove unnecessary quotes
  kebechet/managers/update/messages.py
Labels: approved, size/XS

#590 Updated source-management and fixed version test
  Pipfile.lock
  kebechet/managers/version/version_test.py
Labels: approved, size/XL

#592 Release of version 1.0.10
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/S

#593 upgrade pip for kebechet container image
  Dockerfile
Labels: approved, size/XS

#594 Added modifications to use gitpython
  .pre-commit-config.yaml
  Pipfile.lock
  kebechet/managers/__init__.py
  kebechet/managers/info/info.py
  kebechet/managers/manager.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/thoth_provenance/thoth_provenance.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
  kebechet/services.py
  kebechet/utils.py
Labels: approved, size/L

#596 Release of version 1.1.0
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/XS

#597 Update manager non-atomic updates
  Dockerfile
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
Labels: approved, size/L

#599 Release of version 1.1.1
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/XS

#602 Updated to pipenv 2020
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#600 Add AICOE Config
  .aicoe-ci.yaml
Labels: approved, size/S

#611 Add Sai to project owners
  OWNERS
Labels: approved, size/XS

#615 Req was using pipenv 2018
  requirements.txt
Labels: approved, size/XS

#606 The release PR should close the issue
  kebechet/managers/version/version.py
Labels: approved, size/XS

#627 Fix links set
  kebechet/managers/update/update.py
Labels: approved, size/XS
