Repository thoth-station/kebechet, pull requests merged in 2020-09, with the labels that each got.

#525 Fix formatting when wrong version identifier is found
  kebechet/managers/version/version.py
Labels: approved, size/XS

#522 Fix reStructuredText issues
  README.rst
Labels: approved, size/XS

#530 Automatic update of dependency thoth-glyph from 0.1.0 to 0.1.1
  Pipfile.lock
Labels: approved, bot, size/L

#529 Automatic update of dependency sentry-sdk from 0.17.0 to 0.17.4
  Pipfile.lock
Labels: approved, bot, size/L

#531 Automatic update of dependency gitpython from 3.1.7 to 3.1.8
  Pipfile.lock
Labels: approved, bot, size/L

#528 Automatic update of dependency thamos from 0.11.1 to 0.12.2
  Pipfile.lock
Labels: approved, bot, size/L

#527 Automatic update of dependency thoth-common from 0.16.1 to 0.18.2
  Pipfile.lock
Labels: approved, bot, size/L

#535 Update .thoth.yaml
  .thoth.yaml
Labels: size/XS

#538 Release of version 1.0.5
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/S

#547 Update versions
  Pipfile.lock
Labels: approved, size/L

#550 Release of version 1.0.6
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/XS

#555 fixed imports
  Pipfile.lock
  kebechet/managers/update/update.py
Labels: approved, size/L

#557 Release of version 1.0.7
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/XS

#561 Updated glyph to 0.13
  Pipfile.lock
Labels: approved, size/S

#563 Release of version 1.0.8
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/XS

#567 Updated glyph
  Pipfile.lock
Labels: approved, size/M

#564 Updated version test
  kebechet/managers/version/version_test.py
Labels: approved, size/XS

#569 Release of version 1.0.9
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, bot, size/S

#572 Add manual request example
  kebechet/managers/update/README.rst
Labels: approved, size/S
