Repository thoth-station/kebechet, pull requests merged in 2020-05, with the labels that each got.

#376 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#373 Added instruction for manual trigger and closses issue
  kebechet/managers/update/README.rst
  kebechet/managers/update/update.py
Labels: approved, size/S

#378 Automatic update of dependency gitpython from 3.1.1 to 3.1.2
  Pipfile.lock
Labels: bot, size/M

#379 Automatic update of dependency pylint from 2.5.0 to 2.5.1
  Pipfile.lock
Labels: bot, size/XS

#380 Automatic update of dependency pylint from 2.5.1 to 2.5.2
  Pipfile.lock
Labels: bot, size/XS

#382 Automatic update of dependency semver from 2.9.1 to 2.10.0
  Pipfile.lock
Labels: bot, size/XS

#384 Added source management
  config/thoth.yaml
Labels: approved, size/S

#385 Added sesheta as mainatianer in version manager
  config/thoth.yaml
Labels: approved, size/M

#386 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/M

#260 Make `v` optional in tag when matching version
  kebechet/managers/version/version.py
  kebechet/managers/version/version_test.py
Labels: approved, size/M

#388 Automatic update of dependency thoth-sourcemanagement from 0.2.7 to 0.2.9
  Pipfile.lock
Labels: bot, size/S

#387 Fix test imports
  kebechet/managers/version/version_test.py
Labels: approved, size/XS

#390 Update README.rst
  kebechet/managers/thoth_advise/README.rst
Labels: approved, size/XS

#389 Update README
  kebechet/managers/update/README.rst
Labels: approved, size/XS

#395 Automatic update of dependency semver from 2.10.0 to 2.10.1
  Pipfile.lock
Labels: bot, size/S

#396 Automatic update of dependency toml from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S

#397 Added update and version to slo
  config/thoth.yaml
Labels: approved, size/S

#392 Log info
  kebechet/cli.py
Labels: approved, size/XS

#398 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot, size/M

#399 Automatic update of dependency thamos from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/XS

#381 Fix if automatic relocking PR exists
  kebechet/managers/update/update.py
Labels: size/M

#400 Revert "Fix if automatic relocking PR exists"
  kebechet/managers/update/update.py
Labels: size/M

#402 Added repo
  config/thoth.yaml
Labels: approved, size/S

#403 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/M

#394 use metadata option when calling thamos advise
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/XS

#404 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/S

#405 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#406 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/XS

#407 Automatic update of dependency thamos from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#409 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/XS

#411 Consider app.py and wsgi.py as a source for version
  kebechet/managers/version/version.py
Labels: approved, size/XS

#412 Automatic update of dependency pipenv from 2018.11.26 to 2020.5.28
  Pipfile.lock
Labels: bot, size/M
