Repository thoth-station/kebechet, pull requests merged in 2020-01, with the labels that each got.

#286 Add new maintainer
  config/thoth.yaml
Labels: approved, size/XS

#288 Support for AICoE SrcOpsMetrics
  config/thoth.yaml
Labels: approved, size/XS

#289 kebechet also support release of AICoE SrcOpsMetrics
  config/thoth.yaml
Labels: approved, size/S

#285 Happy new year!
  kebechet/cli.py
  kebechet/config.py
  kebechet/enums.py
  kebechet/exception.py
  kebechet/managers/info/info.py
  kebechet/managers/info/messages.py
  kebechet/managers/manager.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/thoth_advise/__init__.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/thoth_provenance/__init__.py
  kebechet/managers/thoth_provenance/thoth_provenance.py
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
  kebechet/services.py
  kebechet/source_management.py
  kebechet/utils.py
Labels: approved, size/M

#290 Add new mantainer
  config/thoth.yaml
Labels: approved, size/XS

#291 please help me with myreponame
  config/thoth.yaml
Labels: approved, size/S

#292 Introduce second instance of Kebechet
  config/aicoe.yaml
  config/thoth.yaml
Labels: approved, size/L
