Repository thoth-station/kebechet, pull requests merged in 2020-12, with the labels that each got.

#628 Added warning if release tag is missing.
  kebechet/managers/version/messages.py
  kebechet/managers/version/version.py
Labels: approved, size/M

#633 Fixed wrong function accessed
  kebechet/managers/manager.py
Labels: approved, size/XS

#631 newline adjustment for consistency of body for different kind of issues
  kebechet/managers/version/version.py
Labels: approved, size/XS

#635 statisfy the need of python38-devel libraries
  Dockerfile
Labels: approved, size/XS

#621 port to python 38
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#645 Missing typing extensions
  Pipfile
  Pipfile.lock
  requirements.txt
Labels: approved, size/S

#646 Relock to fix typing_extensions relock
  Pipfile.lock
Labels: approved, size/S

#650 fix the name of the imagestream to-be looked up
  .aicoe-ci.yaml
Labels: approved, size/XS

#607 add a little more linky footer to PRs
  .pre-commit-config.yaml
  kebechet/config.py
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
Labels: approved, size/M
