Repository thoth-station/kebechet, pull requests merged in 2020-04, with the labels that each got.

#339 Add support for advise-reporter
  config/thoth.yaml
Labels: approved, size/XS

#340 Added error handling in case version control is used
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
Labels: approved, size/M

#341 Automatic update of dependency thoth-common from 0.10.11 to 0.12.6
  Pipfile.lock
Labels: bot, size/L

#342 Automatic update of dependency thamos from 0.8.1 to 0.9.1
  Pipfile.lock
Labels: bot, size/XS

#343 Automatic update of dependency thoth-sourcemanagement from 0.2.6 to 0.2.7
  Pipfile.lock
Labels: bot, size/XS

#345 Automatic update of dependency thamos from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot, size/XS

#346 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/M

#347 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#348 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/XS

#349 Added s2i notebook repos
  config/thoth.yaml
Labels: approved, size/S

#350 Automatic update of dependency gitpython from 3.1.0 to 3.1.1
  Pipfile.lock
Labels: bot, size/M

#351 Fix Job Template
  openshift/job-kebechet-template.yaml
Labels: approved, size/XS

#352 Fixed run-url cli error
  kebechet/cli.py
Labels: approved, size/XS

#353 Fix parameters
  kebechet/cli.py
Labels: approved, size/XS

#355 Fix liveness
  openshift/job-kebechet-template.yaml
Labels: approved, size/XS

#356 Add maintainer for thamos
  config/thoth.yaml
Labels: approved, size/XS

#357 Added cli endpoint envvar
  kebechet/cli.py
Labels: approved, size/XS

#358 Automatic update of dependency thamos from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot, size/L

#360 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/M

#359 Add SLO-reporter repo
  config/thoth.yaml
Labels: approved, size/S

#362 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/M

#363 Automatic update of dependency pylint from 2.4.4 to 2.5.0
  Pipfile.lock
Labels: bot, size/M

#361 Added argo workflow and oc template
  openshift/kebechet-template.yaml
  workflows/templates/kebechet-job.yaml
Labels: approved, size/L

#364 Automatic update of dependency click from 7.1.1 to 7.1.2
  Pipfile.lock
Labels: bot, size/XS

#365 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/XS

#366 Automatic update of dependency thamos from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot, size/XS

#369 Changed image source to thoth-infra-stage
  openshift/kebechet-template.yaml
Labels: approved, size/XS

#370 Automatic update of dependency thamos from 0.9.4 to 0.10.0
  Pipfile.lock
Labels: bot, size/S

#371 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot
