Repository thoth-station/kebechet, pull requests merged in 2021-01, with the labels that each got.

#656 Thoth Labelmanager
  kebechet/managers/__init__.py
  kebechet/managers/label_bot/README.rst
  kebechet/managers/label_bot/__init__.py
  kebechet/managers/label_bot/label_bot.py
Labels: approved, size/L

#673 Fixed log message
  kebechet/managers/label_bot/label_bot.py
Labels: approved, size/XS

#661 Automatically close update merge request if no longer relevant
  kebechet/managers/update/update.py
Labels: approved, size/S

#686 write outputs of pipenv lock -r to output file
  kebechet/managers/update/update.py
Labels: approved, size/XS
