Repository thoth-station/kebechet, pull requests merged in 2021-08, with the labels that each got.

#769 add args to get access token
  kebechet/utils.py
Labels: approved, size/XS

#771 open issues on repo when managers fail
  kebechet/kebechet_runners.py
  kebechet/managers/manager.py
  kebechet/utils.py
Labels: approved, size/M

#760 advise manager with overlays
  Pipfile.lock
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/M

#778 removed unused -dev dependencies
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#791 Format traceback with Python backtick code
  kebechet/utils.py
Labels: approved, size/XS

#796 if requirements.txt does not exist it must be created
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
Labels: approved, size/S

#798 pull runtime_environment directly from advise results
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/S

#801 convert README from RST to MD
  README.md
  README.rst
  setup.py
Labels: approved
