Repository thoth-station/kebechet, pull requests merged in 2021-11, with the labels that each got.

#886 Add Goern, Harshad and Pep as approvers
  OWNERS
Labels: approved, size/XS

#885 use https based url in the pre-commit
  .pre-commit-config.yaml
Labels: approved, size/XS, lgtm

#883 Support python 3.9 in kebechet dependency management
  Dockerfile
Labels: approved, size/XS, lgtm

#892 add keb version to issue body
  kebechet/utils.py
Labels: approved, lgtm, size/S

#850 use sphinx for Kebechet documentation
  .pre-commit-config.yaml
  MANIFEST.in
  README.md
  README.rst
  docs/Makefile
  docs/authentication.rst
  docs/conf.py
  docs/configuration.rst
  docs/examples/templates/kebechet-run-url.rst
  docs/getting-started.rst
  docs/index.rst
  docs/make.bat
  docs/managers.rst
  docs/managers/info_manager.rst
  docs/managers/label_bot.rst
  docs/managers/pipfile_requirements.rst
  docs/managers/thoth_advise.rst
  docs/managers/thoth_provenance.rst
  docs/managers/update.rst
  docs/managers/version.rst
  kebechet/managers/info/README.rst
  kebechet/managers/label_bot/README.rst
  kebechet/managers/pipfile_requirements/README.rst
  kebechet/managers/thoth_advise/README.rst
  kebechet/managers/thoth_provenance/README.rst
  kebechet/managers/update/README.rst
  kebechet/managers/version/README.rst
  setup.py
Labels: approved, size/XXL

#900 patch the fasttext version for build fix
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#893 Track advise status using GitHub issues
  kebechet/managers/__init__.py
  kebechet/managers/exceptions.py
  kebechet/managers/manager.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/thoth_advise/messages.py
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/L

#904 Remove the maintainers section from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#881 reraise github server exception
  kebechet/kebechet_runners.py
Labels: approved, size/XS

#908 if we have already cloned to dir, return repo from dir
  kebechet/utils.py
Labels: approved, size/XS

#909 check if .git exists so that we don't catch all gitcommand exceptions
  kebechet/utils.py
Labels: approved, size/XS

#915 Clean repo after using
  kebechet/utils.py
Labels: approved, size/S

#916 add kebechet- to all branch names
  kebechet/managers/config_initializer/config_initializer.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/version/version.py
Labels: approved, size/XS, lgtm

#919 No computed changelog
  kebechet/utils.py
Labels: approved, size/XS

#929 Fix format string reference to environment name
  kebechet/managers/update/messages.py
Labels: approved, size/XS

#933 Runtime environment name must not use colon
  .thoth.yaml
Labels: approved, size/XS, lgtm
