Repository thoth-station/kebechet, pull requests merged in 2021-06, with the labels that each got.

#737 add ogr dep to Pipfile
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#744 Prepend changes instead of Appending to Changelog
  .gitignore
  kebechet/managers/version/README.rst
  kebechet/managers/version/version.py
Labels: approved, size/M

#750 use ogr to get app auth token
  kebechet/utils.py
Labels: approved, size/XS

#739 add docs for locally running Kebechet
  README.rst
Labels: approved, lgtm, size/S

#719 use thamos.lib.write_files
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, lgtm, size/S

#749 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, lgtm, size/S

#754 use upstream solution for adding assignees
  Pipfile.lock
  kebechet/managers/manager.py
  kebechet/managers/version/version.py
Labels: approved, lgtm, size/M

#756 fixed bug with unrelated histories where khebhut doesn't create PR
  kebechet/managers/version/version.py
Labels: approved, size/XS

#734 pass environment name to managers and add documentation for expected …
  kebechet/cli.py
  kebechet/kebechet_runners.py
  kebechet/managers/README.rst
  kebechet/managers/manager.py
Labels: approved, size/L

#759 fix issue 746
  kebechet/utils.py
Labels: approved, size/XS
