Repository thoth-station/kebechet, pull requests merged in 2021-09, with the labels that each got.

#808 updated README files to reflect current state of Kebechet
  README.md
  kebechet/managers/README.rst
  kebechet/managers/info/README.rst
  kebechet/managers/label_bot/README.rst
  kebechet/managers/pipfile_requirements/README.rst
  kebechet/managers/thoth_advise/README.rst
  kebechet/managers/thoth_provenance/README.rst
  kebechet/managers/update/README.rst
  kebechet/managers/version/README.rst
Labels: approved, size/L

#810 instead of opening issues in user repo open in thoth-station/support
  kebechet/kebechet_runners.py
Labels: approved, size/XS

#803 add unregistered manager which adds thoth-config
  MANIFEST.in
  kebechet/kebechet_runners.py
  kebechet/managers/__init__.py
  kebechet/managers/config_initializer/__init__.py
  kebechet/managers/config_initializer/config_initializer.py
  kebechet/managers/config_initializer/resources/__init__.py
  kebechet/managers/config_initializer/resources/simple.thoth.yaml
Labels: approved, size/L

#818 add link to repository which caused exception
  kebechet/kebechet_runners.py
  kebechet/utils.py
Labels: approved, size/S

#823 fix some typos
  kebechet/managers/update/messages.py
Labels: approved, size/XS

#821 do not raise issue for conn error
  kebechet/kebechet_runners.py
Labels: approved, size/S

#836 add KPostOffice to approvers
  OWNERS
Labels: approved, size/XS

#829 Fix markdown format for table rows
  kebechet/managers/update/update.py
Labels: approved, size/XS

#835 only create one issue per exc type
  kebechet/utils.py
Labels: approved, size/S

#806 Minor format improvements in the README
  README.md
Labels: approved, size/S

#816 get relative path of overlay currently being updated for link
  kebechet/managers/update/update.py
Labels: approved, size/M
