Repository thoth-station/kebechet, pull requests merged in 2022-02, with the labels that each got.

#990 set badges for easy access to content
  README.rst
Labels: approved, size/XS

#995 use consistent name for 'has_prev_release'
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/version/release_triggers.py
  kebechet/managers/version/version.py
Labels: approved, lgtm, size/S

#1005 Update the label to use on issue creation
  kebechet/managers/update/messages.py
Labels: approved, size/XS

#1001 Add commit hashes to the changelog entries
  kebechet/managers/version/utils.py
Labels: approved, size/XS

#1004 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  .prow.yaml
Labels: approved, size/M
