Repository thoth-station/kebechet, pull requests merged in 2022-07, with the labels that each got.

#1076 Replace 'pipenv install' command to 'pipenv lock' to skip installation which was failed from missing Cmake dependency
  kebechet/managers/update/update.py
Labels: approved, size/XS

#1082 Fix: Refer key 'parameters' directly
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/XS, lgtm

#1081 Issue: Kebechet was picking approvers from it's own OWNERS file
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/XS, lgtm

#1087 bugfix: make labels for update manager default to empty list
  kebechet/managers/update/update.py
Labels: approved, size/XS, lgtm

#1080 A more informative version manager message around wrong versions
  kebechet/managers/version/messages.py
  kebechet/managers/version/release_triggers.py
Labels: approved, size/M, lgtm

#1093 fix: change the import method of managerbase in release_version
  kebechet/managers/version/release_triggers.py
Labels: approved, size/XS

#1096 Fix: To check if kebechet's advise manager is working on all overlays
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/S

#1098 Prevent the Kebechet advice manager from initiating multiple advice requests
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/XS
