Repository thoth-station/kebechet, pull requests merged in 2022-09, with the labels that each got.

#1124 Mask git clone https token from logs
  kebechet/utils.py
Labels: approved, size/M

#1120 Add environment details in PR body
  kebechet/managers/manager.py
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
Labels: approved, size/S

#1131 check to make sure pr exists before attempting rebase on remote branch
  kebechet/managers/update/utils.py
Labels: approved, size/XS, lgtm

#1130 Use lock when updating the dependencies to avoid resource limitations
  kebechet/managers/update/update.py
Labels: approved, size/XS, lgtm

#1138 Type cast the type to pass typechecking
  kebechet/utils.py
Labels: approved, size/XS

#1139 Release of version 1.10.5
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, size/XS, ok-to-test

#1140 Remove checks for git and local path from pipfile
  kebechet/managers/update/update.py
Labels: approved, size/M, lgtm
