Repository thoth-station/kebechet, pull requests merged in 2022-06, with the labels that each got.

#1058 Tag creation in kebechet with release option
  kebechet/managers/version/utils.py
  kebechet/managers/version/version.py
Labels: approved, size/M, lgtm

#1065 Cleanup branch after PR is merged and tag is created
  kebechet/managers/manager.py
  kebechet/managers/version/version.py
Labels: approved, size/S

#1073 add documentation for PR labels for version manager
  docs/managers/version.rst
Labels: approved, lgtm, size/S

#1074 fetch branch using git.fetch before trying to use it
  kebechet/managers/config_initializer/config_initializer.py
  kebechet/managers/update/utils.py
  kebechet/utils.py
Labels: approved, lgtm, size/S
