Repository thoth-station/kebechet, pull requests merged in 2022-10, with the labels that each got.

#1155 add check for no PRs opened
  kebechet/managers/update/update.py
Labels: approved, size/S

#1141 Format package names in GitHub issues
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
Labels: approved, size/XS

#1162 add line to checkout default branch after pushing changes
  kebechet/managers/update/update.py
Labels: approved, lgtm, size/S

#1156 Add 'allow' and 'disallow' setting to each manager
  docs/managers.rst
  kebechet/kebechet_runners.py
  kebechet/managers/manager.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/update/update.py
Labels: approved, size/L, lgtm
