Repository thoth-station/kebechet, pull requests merged in 2022-11, with the labels that each got.

#1165 add signing to kebechet commits
  kebechet/managers/config_initializer/config_initializer.py
  kebechet/managers/manager.py
  kebechet/managers/pipfile_requirements/pipfile_requirements.py
  kebechet/managers/thoth_advise/thoth_advise.py
  kebechet/managers/update/update.py
  kebechet/managers/version/version.py
Labels: approved, size/M, lgtm

#1163 Add pyproject.toml to maintain version from Kebechet's version manager
  .pre-commit-config.yaml
  docs/managers/version.rst
  kebechet/managers/version/messages.py
  kebechet/managers/version/release_triggers.py
Labels: approved, size/M, lgtm

#1172 add default in case there are no runtime environments
  kebechet/kebechet_runners.py
Labels: approved, size/XS, lgtm

#1171 make PR description independent of issue description
  kebechet/managers/version/release_triggers.py
Labels: approved, size/M, lgtm

#1176 Use git add command instead of index.add from gitpython
  kebechet/managers/manager.py
Labels: approved, size/XS

#1178 :ship: Release of version 1.11.1
  CHANGELOG.md
  kebechet/__init__.py
Labels: size/S
