Repository thoth-station/kebechet, pull requests merged in 2022-08, with the labels that each got.

#1106 add type annotations for urllib3.util.Url unpacking
  kebechet/kebechet_runners.py
Labels: approved, size/XS

#1101 Update Dockerfile with cmake dependency
  Dockerfile
Labels: approved, size/XS

#1108 Add configuration for support issue creation
  kebechet/kebechet_runners.py
Labels: approved, lgtm, size/S

#1109 call sync when generating dependency graph
  kebechet/managers/manager.py
Labels: approved, size/XS

#1110 remove hidden files during os walk
  kebechet/managers/version/release_triggers.py
Labels: approved, size/XS, lgtm

#1111 download owners file from repo
  kebechet/managers/version/version.py
Labels: approved, size/XS, lgtm

#1118 Fix: To overwrite same PR with multiple piplock file
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/XS

#1119 Point the closing comment with Pull request link
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
Labels: approved, size/M
