Repository thoth-station/kebechet, pull requests merged in 2022-01, with the labels that each got.

#951 add link to manager doc above managers block in minimal yaml
  kebechet/managers/config_initializer/resources/simple.thoth.yaml
Labels: approved, size/XS

#920 Rebase PRs on top of target branch
  kebechet/managers/manager.py
  kebechet/managers/update/messages.py
  kebechet/managers/update/update.py
  kebechet/managers/update/utils.py
  kebechet/managers/version/version.py
  kebechet/utils.py
Labels: approved, size/L

#877 update version manager to act on PR merge with labels
  kebechet/__init__.py
  kebechet/kebechet_runners.py
  kebechet/managers/version/constants.py
  kebechet/managers/version/exceptions.py
  kebechet/managers/version/messages.py
  kebechet/managers/version/release_triggers.py
  kebechet/managers/version/utils.py
  kebechet/managers/version/version.py
  kebechet/utils.py
Labels: approved, size/XXL

#952 add documentation for advise issue
  docs/managers/thoth_advise.rst
Labels: approved, size/XS

#954 use analysis-id 4 branch name to avoid collisions
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/XS

#946 Suggest users to use Thamos CLI to create requirements file
  kebechet/managers/update/messages.py
Labels: approved, size/XS

#965 remove all references to get user
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/XS

#964 Unpin fasttext version from Pipfile
  Pipfile
Labels: approved, size/XS

#971 Enable TLS verification
  .thoth.yaml
Labels: approved, size/XS

#970 Enable TLS verification in the sample default configuration
  kebechet/managers/config_initializer/resources/simple.thoth.yaml
Labels: approved, size/XS

#974 pop enabled config
  kebechet/kebechet_runners.py
Labels: approved, size/XS

#973 check before trying to unshallow a repo
  kebechet/utils.py
Labels: approved, size/XS

#938 Add branch for if thoth configuration blocks advise submission
  kebechet/managers/thoth_advise/thoth_advise.py
Labels: approved, size/M

#979 Release of version 1.7.2
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, ok-to-test

#982 use previous tag for computing changelog
  kebechet/managers/version/utils.py
  kebechet/managers/version/version.py
Labels: approved, size/S

#986 :ship: Release of version 1.7.3
  CHANGELOG.md
  kebechet/__init__.py
Labels: approved, size/S
